# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: juliankings
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: miranda-dashboard
service: nodejs-aws-lambda
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: production
  environment:
    JWT_SECURE_KEY: ${env:JWT_SECURE_KEY}
    SQL_HOST: ${env:SQL_HOST}
    SQL_PORT: ${env:SQL_PORT}
    SQL_DATABASE: ${env:SQL_DATABASE}
    SQL_USER: ${env:SQL_USER}
    SQL_PASSWORD: ${env:SQL_PASSWORD}
    MY_AWS_ACCESS_KEY: ${env:AWS_ACCESS_KEY}
    MY_AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
functions:
  app:
    handler: dist/app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}