# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: juliankings
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: hotel-miranda-api
service: nodejs-aws-lambda
provider:
  name: aws
  runtime: nodejs18.x
package:
  exclude:
    - venv/**
functions:
  app:
    handler: dist/app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    environment:
      JWT_SECURE_KEY: ${{ secrets.JWT_SECURE_KEY }}
      SQL_HOST: ${{ secrets.SQL_HOST }}
      SQL_PORT: ${{ secrets.SQL_PORT }}
      SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
      SQL_USER: ${{ secrets.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}